//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyexFleetManagement.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources_th {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_th() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("StyexFleetManagement.Resx.AppResources.th", typeof(AppResources_th).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string above {
            get {
                return ResourceManager.GetString("above", resourceCulture);
            }
        }
        
        public static string acceleration_label {
            get {
                return ResourceManager.GetString("acceleration_label", resourceCulture);
            }
        }
        
        public static string acceleration_short_title {
            get {
                return ResourceManager.GetString("acceleration_short_title", resourceCulture);
            }
        }
        
        public static string accident_count {
            get {
                return ResourceManager.GetString("accident_count", resourceCulture);
            }
        }
        
        public static string accident_count_dashboard {
            get {
                return ResourceManager.GetString("accident_count_dashboard", resourceCulture);
            }
        }
        
        public static string accident_label {
            get {
                return ResourceManager.GetString("accident_label", resourceCulture);
            }
        }
        
        public static string accident_summary_description {
            get {
                return ResourceManager.GetString("accident_summary_description", resourceCulture);
            }
        }
        
        public static string action_account_settings {
            get {
                return ResourceManager.GetString("action_account_settings", resourceCulture);
            }
        }
        
        public static string action_add_to_favourites {
            get {
                return ResourceManager.GetString("action_add_to_favourites", resourceCulture);
            }
        }
        
        public static string action_change_map_type {
            get {
                return ResourceManager.GetString("action_change_map_type", resourceCulture);
            }
        }
        
        public static string action_clear_cache {
            get {
                return ResourceManager.GetString("action_clear_cache", resourceCulture);
            }
        }
        
        public static string action_logout {
            get {
                return ResourceManager.GetString("action_logout", resourceCulture);
            }
        }
        
        public static string action_refresh {
            get {
                return ResourceManager.GetString("action_refresh", resourceCulture);
            }
        }
        
        public static string action_refresh_user_settings {
            get {
                return ResourceManager.GetString("action_refresh_user_settings", resourceCulture);
            }
        }
        
        public static string action_remove_from_favourites {
            get {
                return ResourceManager.GetString("action_remove_from_favourites", resourceCulture);
            }
        }
        
        public static string action_reset_dashboard_settings {
            get {
                return ResourceManager.GetString("action_reset_dashboard_settings", resourceCulture);
            }
        }
        
        public static string action_share_report {
            get {
                return ResourceManager.GetString("action_share_report", resourceCulture);
            }
        }
        
        public static string alerts {
            get {
                return ResourceManager.GetString("alerts", resourceCulture);
            }
        }
        
        public static string alert_summary_description {
            get {
                return ResourceManager.GetString("alert_summary_description", resourceCulture);
            }
        }
        
        public static string allow_multiple_trip_plotting_lable {
            get {
                return ResourceManager.GetString("allow_multiple_trip_plotting_lable", resourceCulture);
            }
        }
        
        public static string all_label {
            get {
                return ResourceManager.GetString("all_label", resourceCulture);
            }
        }
        
        public static string app_is_recording {
            get {
                return ResourceManager.GetString("app_is_recording", resourceCulture);
            }
        }
        
        public static string app_is_running {
            get {
                return ResourceManager.GetString("app_is_running", resourceCulture);
            }
        }
        
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        public static string authentication_error {
            get {
                return ResourceManager.GetString("authentication_error", resourceCulture);
            }
        }
        
        public static string average {
            get {
                return ResourceManager.GetString("average", resourceCulture);
            }
        }
        
        public static string average_consumption {
            get {
                return ResourceManager.GetString("average_consumption", resourceCulture);
            }
        }
        
        public static string average_fuel_consumption {
            get {
                return ResourceManager.GetString("average_fuel_consumption", resourceCulture);
            }
        }
        
        public static string average_short {
            get {
                return ResourceManager.GetString("average_short", resourceCulture);
            }
        }
        
        public static string average_speed {
            get {
                return ResourceManager.GetString("average_speed", resourceCulture);
            }
        }
        
        public static string back_button {
            get {
                return ResourceManager.GetString("back_button", resourceCulture);
            }
        }
        
        public static string below {
            get {
                return ResourceManager.GetString("below", resourceCulture);
            }
        }
        
        public static string brakes_title {
            get {
                return ResourceManager.GetString("brakes_title", resourceCulture);
            }
        }
        
        public static string braking_label {
            get {
                return ResourceManager.GetString("braking_label", resourceCulture);
            }
        }
        
        public static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        public static string button_login {
            get {
                return ResourceManager.GetString("button_login", resourceCulture);
            }
        }
        
        public static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }
        
        public static string button_plot {
            get {
                return ResourceManager.GetString("button_plot", resourceCulture);
            }
        }
        
        public static string button_poll {
            get {
                return ResourceManager.GetString("button_poll", resourceCulture);
            }
        }
        
        public static string coming_soon {
            get {
                return ResourceManager.GetString("coming_soon", resourceCulture);
            }
        }
        
        public static string compliance_label {
            get {
                return ResourceManager.GetString("compliance_label", resourceCulture);
            }
        }
        
        public static string consumption {
            get {
                return ResourceManager.GetString("consumption", resourceCulture);
            }
        }
        
        public static string consumption_measures_description {
            get {
                return ResourceManager.GetString("consumption_measures_description", resourceCulture);
            }
        }
        
        public static string consumption_short {
            get {
                return ResourceManager.GetString("consumption_short", resourceCulture);
            }
        }
        
        public static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        public static string cornering_label {
            get {
                return ResourceManager.GetString("cornering_label", resourceCulture);
            }
        }
        
        public static string cost {
            get {
                return ResourceManager.GetString("cost", resourceCulture);
            }
        }
        
        public static string custom {
            get {
                return ResourceManager.GetString("custom", resourceCulture);
            }
        }
        
        public static string custom_data_summary_description {
            get {
                return ResourceManager.GetString("custom_data_summary_description", resourceCulture);
            }
        }
        
        public static string custom_end_date {
            get {
                return ResourceManager.GetString("custom_end_date", resourceCulture);
            }
        }
        
        public static string custom_start_date {
            get {
                return ResourceManager.GetString("custom_start_date", resourceCulture);
            }
        }
        
        public static string custom_value {
            get {
                return ResourceManager.GetString("custom_value", resourceCulture);
            }
        }
        
        public static string daily_avg {
            get {
                return ResourceManager.GetString("daily_avg", resourceCulture);
            }
        }
        
        public static string dashboard_title {
            get {
                return ResourceManager.GetString("dashboard_title", resourceCulture);
            }
        }
        
        public static string date_range {
            get {
                return ResourceManager.GetString("date_range", resourceCulture);
            }
        }
        
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        public static string device_activity_dashboard {
            get {
                return ResourceManager.GetString("device_activity_dashboard", resourceCulture);
            }
        }
        
        public static string device_id {
            get {
                return ResourceManager.GetString("device_id", resourceCulture);
            }
        }
        
        public static string distance {
            get {
                return ResourceManager.GetString("distance", resourceCulture);
            }
        }
        
        public static string distance_average_total {
            get {
                return ResourceManager.GetString("distance_average_total", resourceCulture);
            }
        }
        
        public static string distance_km {
            get {
                return ResourceManager.GetString("distance_km", resourceCulture);
            }
        }
        
        public static string distance_km_abbr {
            get {
                return ResourceManager.GetString("distance_km_abbr", resourceCulture);
            }
        }
        
        public static string distance_marker {
            get {
                return ResourceManager.GetString("distance_marker", resourceCulture);
            }
        }
        
        public static string distance_miles {
            get {
                return ResourceManager.GetString("distance_miles", resourceCulture);
            }
        }
        
        public static string distance_miles_abbr {
            get {
                return ResourceManager.GetString("distance_miles_abbr", resourceCulture);
            }
        }
        
        public static string distance_nautical_miles {
            get {
                return ResourceManager.GetString("distance_nautical_miles", resourceCulture);
            }
        }
        
        public static string distance_nautical_miles_abbr {
            get {
                return ResourceManager.GetString("distance_nautical_miles_abbr", resourceCulture);
            }
        }
        
        public static string distance_short_title {
            get {
                return ResourceManager.GetString("distance_short_title", resourceCulture);
            }
        }
        
        public static string distance_with_value {
            get {
                return ResourceManager.GetString("distance_with_value", resourceCulture);
            }
        }
        
        public static string dist_driven_dashboard {
            get {
                return ResourceManager.GetString("dist_driven_dashboard", resourceCulture);
            }
        }
        
        public static string driver_code {
            get {
                return ResourceManager.GetString("driver_code", resourceCulture);
            }
        }
        
        public static string driver_count {
            get {
                return ResourceManager.GetString("driver_count", resourceCulture);
            }
        }
        
        public static string driver_label {
            get {
                return ResourceManager.GetString("driver_label", resourceCulture);
            }
        }
        
        public static string driver_route_description {
            get {
                return ResourceManager.GetString("driver_route_description", resourceCulture);
            }
        }
        
        public static string driver_stats_description {
            get {
                return ResourceManager.GetString("driver_stats_description", resourceCulture);
            }
        }
        
        public static string drive_duration {
            get {
                return ResourceManager.GetString("drive_duration", resourceCulture);
            }
        }
        
        public static string drive_duration_dashboard {
            get {
                return ResourceManager.GetString("drive_duration_dashboard", resourceCulture);
            }
        }
        
        public static string driving {
            get {
                return ResourceManager.GetString("driving", resourceCulture);
            }
        }
        
        public static string driving_time {
            get {
                return ResourceManager.GetString("driving_time", resourceCulture);
            }
        }
        
        public static string dtc_code_maintenance_description {
            get {
                return ResourceManager.GetString("dtc_code_maintenance_description", resourceCulture);
            }
        }
        
        public static string duration_marker {
            get {
                return ResourceManager.GetString("duration_marker", resourceCulture);
            }
        }
        
        public static string duration_short_title {
            get {
                return ResourceManager.GetString("duration_short_title", resourceCulture);
            }
        }
        
        public static string duration_with_value {
            get {
                return ResourceManager.GetString("duration_with_value", resourceCulture);
            }
        }
        
        public static string end {
            get {
                return ResourceManager.GetString("end", resourceCulture);
            }
        }
        
        public static string end_date {
            get {
                return ResourceManager.GetString("end_date", resourceCulture);
            }
        }
        
        public static string end_location {
            get {
                return ResourceManager.GetString("end_location", resourceCulture);
            }
        }
        
        public static string entries {
            get {
                return ResourceManager.GetString("entries", resourceCulture);
            }
        }
        
        public static string error_dashboard_tile {
            get {
                return ResourceManager.GetString("error_dashboard_tile", resourceCulture);
            }
        }
        
        public static string error_label {
            get {
                return ResourceManager.GetString("error_label", resourceCulture);
            }
        }
        
        public static string error_loading_report {
            get {
                return ResourceManager.GetString("error_loading_report", resourceCulture);
            }
        }
        
        public static string error_position {
            get {
                return ResourceManager.GetString("error_position", resourceCulture);
            }
        }
        
        public static string error_trip_information {
            get {
                return ResourceManager.GetString("error_trip_information", resourceCulture);
            }
        }
        
        public static string exceptions {
            get {
                return ResourceManager.GetString("exceptions", resourceCulture);
            }
        }
        
        public static string exception_acceleration {
            get {
                return ResourceManager.GetString("exception_acceleration", resourceCulture);
            }
        }
        
        public static string exception_accident {
            get {
                return ResourceManager.GetString("exception_accident", resourceCulture);
            }
        }
        
        public static string exception_alerts_label {
            get {
                return ResourceManager.GetString("exception_alerts_label", resourceCulture);
            }
        }
        
        public static string exception_cornering {
            get {
                return ResourceManager.GetString("exception_cornering", resourceCulture);
            }
        }
        
        public static string exception_count {
            get {
                return ResourceManager.GetString("exception_count", resourceCulture);
            }
        }
        
        public static string exception_freewheeling {
            get {
                return ResourceManager.GetString("exception_freewheeling", resourceCulture);
            }
        }
        
        public static string exception_harshbreaking {
            get {
                return ResourceManager.GetString("exception_harshbreaking", resourceCulture);
            }
        }
        
        public static string exception_idle {
            get {
                return ResourceManager.GetString("exception_idle", resourceCulture);
            }
        }
        
        public static string exception_lanechange {
            get {
                return ResourceManager.GetString("exception_lanechange", resourceCulture);
            }
        }
        
        public static string exception_recklessdriving {
            get {
                return ResourceManager.GetString("exception_recklessdriving", resourceCulture);
            }
        }
        
        public static string exception_rpm {
            get {
                return ResourceManager.GetString("exception_rpm", resourceCulture);
            }
        }
        
        public static string exception_speeding {
            get {
                return ResourceManager.GetString("exception_speeding", resourceCulture);
            }
        }
        
        public static string exception_summary_description {
            get {
                return ResourceManager.GetString("exception_summary_description", resourceCulture);
            }
        }
        
        public static string exception_swerving {
            get {
                return ResourceManager.GetString("exception_swerving", resourceCulture);
            }
        }
        
        public static string exception_title {
            get {
                return ResourceManager.GetString("exception_title", resourceCulture);
            }
        }
        
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        public static string fleet_exceptions {
            get {
                return ResourceManager.GetString("fleet_exceptions", resourceCulture);
            }
        }
        
        public static string fleet_utilization_description {
            get {
                return ResourceManager.GetString("fleet_utilization_description", resourceCulture);
            }
        }
        
        public static string fleet_utilization_report {
            get {
                return ResourceManager.GetString("fleet_utilization_report", resourceCulture);
            }
        }
        
        public static string freewheeling_label {
            get {
                return ResourceManager.GetString("freewheeling_label", resourceCulture);
            }
        }
        
        public static string fuel {
            get {
                return ResourceManager.GetString("fuel", resourceCulture);
            }
        }
        
        public static string fuel_consumption {
            get {
                return ResourceManager.GetString("fuel_consumption", resourceCulture);
            }
        }
        
        public static string fuel_cons_dashboard_label {
            get {
                return ResourceManager.GetString("fuel_cons_dashboard_label", resourceCulture);
            }
        }
        
        public static string fuel_cost {
            get {
                return ResourceManager.GetString("fuel_cost", resourceCulture);
            }
        }
        
        public static string fuel_cost_per_km {
            get {
                return ResourceManager.GetString("fuel_cost_per_km", resourceCulture);
            }
        }
        
        public static string fuel_entry_consumption_description {
            get {
                return ResourceManager.GetString("fuel_entry_consumption_description", resourceCulture);
            }
        }
        
        public static string fuel_entry_costs_description {
            get {
                return ResourceManager.GetString("fuel_entry_costs_description", resourceCulture);
            }
        }
        
        public static string fuel_entry_summary_description {
            get {
                return ResourceManager.GetString("fuel_entry_summary_description", resourceCulture);
            }
        }
        
        public static string fuel_level {
            get {
                return ResourceManager.GetString("fuel_level", resourceCulture);
            }
        }
        
        public static string fuel_level_monitor_description {
            get {
                return ResourceManager.GetString("fuel_level_monitor_description", resourceCulture);
            }
        }
        
        public static string fuel_marker {
            get {
                return ResourceManager.GetString("fuel_marker", resourceCulture);
            }
        }
        
        public static string fuel_source {
            get {
                return ResourceManager.GetString("fuel_source", resourceCulture);
            }
        }
        
        public static string fuel_theft {
            get {
                return ResourceManager.GetString("fuel_theft", resourceCulture);
            }
        }
        
        public static string fuel_theft_dashboard_label {
            get {
                return ResourceManager.GetString("fuel_theft_dashboard_label", resourceCulture);
            }
        }
        
        public static string fuel_used {
            get {
                return ResourceManager.GetString("fuel_used", resourceCulture);
            }
        }
        
        public static string fuel_used_short {
            get {
                return ResourceManager.GetString("fuel_used_short", resourceCulture);
            }
        }
        
        public static string goal {
            get {
                return ResourceManager.GetString("goal", resourceCulture);
            }
        }
        
        public static string gray_marker_definition {
            get {
                return ResourceManager.GetString("gray_marker_definition", resourceCulture);
            }
        }
        
        public static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        public static string icon {
            get {
                return ResourceManager.GetString("icon", resourceCulture);
            }
        }
        
        public static string idle_dashboard_label {
            get {
                return ResourceManager.GetString("idle_dashboard_label", resourceCulture);
            }
        }
        
        public static string idle_dur {
            get {
                return ResourceManager.GetString("idle_dur", resourceCulture);
            }
        }
        
        public static string idle_label {
            get {
                return ResourceManager.GetString("idle_label", resourceCulture);
            }
        }
        
        public static string idle_time {
            get {
                return ResourceManager.GetString("idle_time", resourceCulture);
            }
        }
        
        public static string idle_time_dashboard {
            get {
                return ResourceManager.GetString("idle_time_dashboard", resourceCulture);
            }
        }
        
        public static string idling {
            get {
                return ResourceManager.GetString("idling", resourceCulture);
            }
        }
        
        public static string invalid_value {
            get {
                return ResourceManager.GetString("invalid_value", resourceCulture);
            }
        }
        
        public static string kpi_alerts_title {
            get {
                return ResourceManager.GetString("kpi_alerts_title", resourceCulture);
            }
        }
        
        public static string label_birthDate {
            get {
                return ResourceManager.GetString("label_birthDate", resourceCulture);
            }
        }
        
        public static string label_canbus {
            get {
                return ResourceManager.GetString("label_canbus", resourceCulture);
            }
        }
        
        public static string label_co2 {
            get {
                return ResourceManager.GetString("label_co2", resourceCulture);
            }
        }
        
        public static string label_driverId {
            get {
                return ResourceManager.GetString("label_driverId", resourceCulture);
            }
        }
        
        public static string label_driver_filtered {
            get {
                return ResourceManager.GetString("label_driver_filtered", resourceCulture);
            }
        }
        
        public static string label_expiraryDate {
            get {
                return ResourceManager.GetString("label_expiraryDate", resourceCulture);
            }
        }
        
        public static string label_fuel_meter {
            get {
                return ResourceManager.GetString("label_fuel_meter", resourceCulture);
            }
        }
        
        public static string label_gender {
            get {
                return ResourceManager.GetString("label_gender", resourceCulture);
            }
        }
        
        public static string label_in_trip {
            get {
                return ResourceManager.GetString("label_in_trip", resourceCulture);
            }
        }
        
        public static string label_is_idling {
            get {
                return ResourceManager.GetString("label_is_idling", resourceCulture);
            }
        }
        
        public static string label_licenceNumber {
            get {
                return ResourceManager.GetString("label_licenceNumber", resourceCulture);
            }
        }
        
        public static string label_licenceType {
            get {
                return ResourceManager.GetString("label_licenceType", resourceCulture);
            }
        }
        
        public static string label_login {
            get {
                return ResourceManager.GetString("label_login", resourceCulture);
            }
        }
        
        public static string label_mass_airflow {
            get {
                return ResourceManager.GetString("label_mass_airflow", resourceCulture);
            }
        }
        
        public static string label_none {
            get {
                return ResourceManager.GetString("label_none", resourceCulture);
            }
        }
        
        public static string label_not_in_trip {
            get {
                return ResourceManager.GetString("label_not_in_trip", resourceCulture);
            }
        }
        
        public static string label_no_trips {
            get {
                return ResourceManager.GetString("label_no_trips", resourceCulture);
            }
        }
        
        public static string label_obdii {
            get {
                return ResourceManager.GetString("label_obdii", resourceCulture);
            }
        }
        
        public static string label_password {
            get {
                return ResourceManager.GetString("label_password", resourceCulture);
            }
        }
        
        public static string label_requires_attention {
            get {
                return ResourceManager.GetString("label_requires_attention", resourceCulture);
            }
        }
        
        public static string label_rfe {
            get {
                return ResourceManager.GetString("label_rfe", resourceCulture);
            }
        }
        
        public static string label_server {
            get {
                return ResourceManager.GetString("label_server", resourceCulture);
            }
        }
        
        public static string label_unknown_vehicle_group {
            get {
                return ResourceManager.GetString("label_unknown_vehicle_group", resourceCulture);
            }
        }
        
        public static string label_updated {
            get {
                return ResourceManager.GetString("label_updated", resourceCulture);
            }
        }
        
        public static string label_username {
            get {
                return ResourceManager.GetString("label_username", resourceCulture);
            }
        }
        
        public static string label_vehicles {
            get {
                return ResourceManager.GetString("label_vehicles", resourceCulture);
            }
        }
        
        public static string landing_page_title {
            get {
                return ResourceManager.GetString("landing_page_title", resourceCulture);
            }
        }
        
        public static string lane_change_label {
            get {
                return ResourceManager.GetString("lane_change_label", resourceCulture);
            }
        }
        
        public static string last_event_received {
            get {
                return ResourceManager.GetString("last_event_received", resourceCulture);
            }
        }
        
        public static string last_known_position {
            get {
                return ResourceManager.GetString("last_known_position", resourceCulture);
            }
        }
        
        public static string last_location {
            get {
                return ResourceManager.GetString("last_location", resourceCulture);
            }
        }
        
        public static string last_reported {
            get {
                return ResourceManager.GetString("last_reported", resourceCulture);
            }
        }
        
        public static string last_trips {
            get {
                return ResourceManager.GetString("last_trips", resourceCulture);
            }
        }
        
        public static string last_x_days {
            get {
                return ResourceManager.GetString("last_x_days", resourceCulture);
            }
        }
        
        public static string last_x_months {
            get {
                return ResourceManager.GetString("last_x_months", resourceCulture);
            }
        }
        
        public static string last_x_weeks {
            get {
                return ResourceManager.GetString("last_x_weeks", resourceCulture);
            }
        }
        
        public static string least_exceptions {
            get {
                return ResourceManager.GetString("least_exceptions", resourceCulture);
            }
        }
        
        public static string least_fuel_efficient {
            get {
                return ResourceManager.GetString("least_fuel_efficient", resourceCulture);
            }
        }
        
        public static string limit_label {
            get {
                return ResourceManager.GetString("limit_label", resourceCulture);
            }
        }
        
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        public static string loading_report {
            get {
                return ResourceManager.GetString("loading_report", resourceCulture);
            }
        }
        
        public static string location_monitor_description {
            get {
                return ResourceManager.GetString("location_monitor_description", resourceCulture);
            }
        }
        
        public static string location_updates {
            get {
                return ResourceManager.GetString("location_updates", resourceCulture);
            }
        }
        
        public static string logging_started {
            get {
                return ResourceManager.GetString("logging_started", resourceCulture);
            }
        }
        
        public static string logging_stopped {
            get {
                return ResourceManager.GetString("logging_stopped", resourceCulture);
            }
        }
        
        public static string login_error_credentials_missing {
            get {
                return ResourceManager.GetString("login_error_credentials_missing", resourceCulture);
            }
        }
        
        public static string login_progress_signing_in {
            get {
                return ResourceManager.GetString("login_progress_signing_in", resourceCulture);
            }
        }
        
        public static string logout_confirmation_question {
            get {
                return ResourceManager.GetString("logout_confirmation_question", resourceCulture);
            }
        }
        
        public static string l_100km {
            get {
                return ResourceManager.GetString("l_100km", resourceCulture);
            }
        }
        
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        public static string map_default_vehicle_group_title {
            get {
                return ResourceManager.GetString("map_default_vehicle_group_title", resourceCulture);
            }
        }
        
        public static string marker_color_codes {
            get {
                return ResourceManager.GetString("marker_color_codes", resourceCulture);
            }
        }
        
        public static string marker_legend_black {
            get {
                return ResourceManager.GetString("marker_legend_black", resourceCulture);
            }
        }
        
        public static string marker_legend_green {
            get {
                return ResourceManager.GetString("marker_legend_green", resourceCulture);
            }
        }
        
        public static string marker_legend_purple {
            get {
                return ResourceManager.GetString("marker_legend_purple", resourceCulture);
            }
        }
        
        public static string marker_legend_red {
            get {
                return ResourceManager.GetString("marker_legend_red", resourceCulture);
            }
        }
        
        public static string marker_legend_yellow {
            get {
                return ResourceManager.GetString("marker_legend_yellow", resourceCulture);
            }
        }
        
        public static string max_rpm {
            get {
                return ResourceManager.GetString("max_rpm", resourceCulture);
            }
        }
        
        public static string max_speed {
            get {
                return ResourceManager.GetString("max_speed", resourceCulture);
            }
        }
        
        public static string max_speed_dashboard {
            get {
                return ResourceManager.GetString("max_speed_dashboard", resourceCulture);
            }
        }
        
        public static string max_speed_label {
            get {
                return ResourceManager.GetString("max_speed_label", resourceCulture);
            }
        }
        
        public static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        public static string more_than_year {
            get {
                return ResourceManager.GetString("more_than_year", resourceCulture);
            }
        }
        
        public static string most_exceptions {
            get {
                return ResourceManager.GetString("most_exceptions", resourceCulture);
            }
        }
        
        public static string most_fuel_efficient {
            get {
                return ResourceManager.GetString("most_fuel_efficient", resourceCulture);
            }
        }
        
        public static string mzone_cost {
            get {
                return ResourceManager.GetString("mzone_cost", resourceCulture);
            }
        }
        
        public static string non_reporting {
            get {
                return ResourceManager.GetString("non_reporting", resourceCulture);
            }
        }
        
        public static string non_reporting_label {
            get {
                return ResourceManager.GetString("non_reporting_label", resourceCulture);
            }
        }
        
        public static string not_available_abbreviation {
            get {
                return ResourceManager.GetString("not_available_abbreviation", resourceCulture);
            }
        }
        
        public static string no_b_licences {
            get {
                return ResourceManager.GetString("no_b_licences", resourceCulture);
            }
        }
        
        public static string no_data_error {
            get {
                return ResourceManager.GetString("no_data_error", resourceCulture);
            }
        }
        
        public static string no_data_message {
            get {
                return ResourceManager.GetString("no_data_message", resourceCulture);
            }
        }
        
        public static string no_favourite_reports {
            get {
                return ResourceManager.GetString("no_favourite_reports", resourceCulture);
            }
        }
        
        public static string no_favourite_reports_description {
            get {
                return ResourceManager.GetString("no_favourite_reports_description", resourceCulture);
            }
        }
        
        public static string no_personal_licences {
            get {
                return ResourceManager.GetString("no_personal_licences", resourceCulture);
            }
        }
        
        public static string no_trips_found {
            get {
                return ResourceManager.GetString("no_trips_found", resourceCulture);
            }
        }
        
        public static string no_t_licences {
            get {
                return ResourceManager.GetString("no_t_licences", resourceCulture);
            }
        }
        
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        public static string number_of_vehicles {
            get {
                return ResourceManager.GetString("number_of_vehicles", resourceCulture);
            }
        }
        
        public static string obd_route_data {
            get {
                return ResourceManager.GetString("obd_route_data", resourceCulture);
            }
        }
        
        public static string operational_alerts_title {
            get {
                return ResourceManager.GetString("operational_alerts_title", resourceCulture);
            }
        }
        
        public static string overtime {
            get {
                return ResourceManager.GetString("overtime", resourceCulture);
            }
        }
        
        public static string overtime_driving {
            get {
                return ResourceManager.GetString("overtime_driving", resourceCulture);
            }
        }
        
        public static string over_speed_dashboard {
            get {
                return ResourceManager.GetString("over_speed_dashboard", resourceCulture);
            }
        }
        
        public static string parked {
            get {
                return ResourceManager.GetString("parked", resourceCulture);
            }
        }
        
        public static string parse_error {
            get {
                return ResourceManager.GetString("parse_error", resourceCulture);
            }
        }
        
        public static string personal_logbook_location_message {
            get {
                return ResourceManager.GetString("personal_logbook_location_message", resourceCulture);
            }
        }
        
        public static string personal_logbook_phone_note {
            get {
                return ResourceManager.GetString("personal_logbook_phone_note", resourceCulture);
            }
        }
        
        public static string personal_logbook_phone_registration_steps {
            get {
                return ResourceManager.GetString("personal_logbook_phone_registration_steps", resourceCulture);
            }
        }
        
        public static string personal_logbook_phone_registration_title {
            get {
                return ResourceManager.GetString("personal_logbook_phone_registration_title", resourceCulture);
            }
        }
        
        public static string per_variable_display_description {
            get {
                return ResourceManager.GetString("per_variable_display_description", resourceCulture);
            }
        }
        
        public static string per_vehicle {
            get {
                return ResourceManager.GetString("per_vehicle", resourceCulture);
            }
        }
        
        public static string phone_id {
            get {
                return ResourceManager.GetString("phone_id", resourceCulture);
            }
        }
        
        public static string please_wait {
            get {
                return ResourceManager.GetString("please_wait", resourceCulture);
            }
        }
        
        public static string poi_activity_description {
            get {
                return ResourceManager.GetString("poi_activity_description", resourceCulture);
            }
        }
        
        public static string poll_command_sent {
            get {
                return ResourceManager.GetString("poll_command_sent", resourceCulture);
            }
        }
        
        public static string pref_currency {
            get {
                return ResourceManager.GetString("pref_currency", resourceCulture);
            }
        }
        
        public static string pref_distance_measurement_unit {
            get {
                return ResourceManager.GetString("pref_distance_measurement_unit", resourceCulture);
            }
        }
        
        public static string pref_fluid_measurement_unit {
            get {
                return ResourceManager.GetString("pref_fluid_measurement_unit", resourceCulture);
            }
        }
        
        public static string previous_month {
            get {
                return ResourceManager.GetString("previous_month", resourceCulture);
            }
        }
        
        public static string previous_week {
            get {
                return ResourceManager.GetString("previous_week", resourceCulture);
            }
        }
        
        public static string ratio {
            get {
                return ResourceManager.GetString("ratio", resourceCulture);
            }
        }
        
        public static string reckless_driving_label {
            get {
                return ResourceManager.GetString("reckless_driving_label", resourceCulture);
            }
        }
        
        public static string registration {
            get {
                return ResourceManager.GetString("registration", resourceCulture);
            }
        }
        
        public static string remove_report_confirmation {
            get {
                return ResourceManager.GetString("remove_report_confirmation", resourceCulture);
            }
        }
        
        public static string reporting_interval {
            get {
                return ResourceManager.GetString("reporting_interval", resourceCulture);
            }
        }
        
        public static string reports_title {
            get {
                return ResourceManager.GetString("reports_title", resourceCulture);
            }
        }
        
        public static string report_title_actions {
            get {
                return ResourceManager.GetString("report_title_actions", resourceCulture);
            }
        }
        
        public static string report_title_alert_notifications {
            get {
                return ResourceManager.GetString("report_title_alert_notifications", resourceCulture);
            }
        }
        
        public static string report_title_alert_summary {
            get {
                return ResourceManager.GetString("report_title_alert_summary", resourceCulture);
            }
        }
        
        public static string report_title_dlt_driver_stats {
            get {
                return ResourceManager.GetString("report_title_dlt_driver_stats", resourceCulture);
            }
        }
        
        public static string report_title_driver_route_activity {
            get {
                return ResourceManager.GetString("report_title_driver_route_activity", resourceCulture);
            }
        }
        
        public static string report_title_driving_summary {
            get {
                return ResourceManager.GetString("report_title_driving_summary", resourceCulture);
            }
        }
        
        public static string report_title_entities {
            get {
                return ResourceManager.GetString("report_title_entities", resourceCulture);
            }
        }
        
        public static string report_title_fleet {
            get {
                return ResourceManager.GetString("report_title_fleet", resourceCulture);
            }
        }
        
        public static string report_title_fleet_accident_summary {
            get {
                return ResourceManager.GetString("report_title_fleet_accident_summary", resourceCulture);
            }
        }
        
        public static string report_title_fleet_custom_data_summary {
            get {
                return ResourceManager.GetString("report_title_fleet_custom_data_summary", resourceCulture);
            }
        }
        
        public static string report_title_fleet_dtc_code_maintenance {
            get {
                return ResourceManager.GetString("report_title_fleet_dtc_code_maintenance", resourceCulture);
            }
        }
        
        public static string report_title_fleet_exception_summary {
            get {
                return ResourceManager.GetString("report_title_fleet_exception_summary", resourceCulture);
            }
        }
        
        public static string report_title_fleet_obd_route_data {
            get {
                return ResourceManager.GetString("report_title_fleet_obd_route_data", resourceCulture);
            }
        }
        
        public static string report_title_fleet_route_activity {
            get {
                return ResourceManager.GetString("report_title_fleet_route_activity", resourceCulture);
            }
        }
        
        public static string report_title_fleet_total_cost_of_ownership {
            get {
                return ResourceManager.GetString("report_title_fleet_total_cost_of_ownership", resourceCulture);
            }
        }
        
        public static string report_title_fleet_utilization {
            get {
                return ResourceManager.GetString("report_title_fleet_utilization", resourceCulture);
            }
        }
        
        public static string report_title_fuel_consumption {
            get {
                return ResourceManager.GetString("report_title_fuel_consumption", resourceCulture);
            }
        }
        
        public static string report_title_fuel_consumption_measures {
            get {
                return ResourceManager.GetString("report_title_fuel_consumption_measures", resourceCulture);
            }
        }
        
        public static string report_title_fuel_cost {
            get {
                return ResourceManager.GetString("report_title_fuel_cost", resourceCulture);
            }
        }
        
        public static string report_title_fuel_entry_consumption {
            get {
                return ResourceManager.GetString("report_title_fuel_entry_consumption", resourceCulture);
            }
        }
        
        public static string report_title_fuel_entry_costs {
            get {
                return ResourceManager.GetString("report_title_fuel_entry_costs", resourceCulture);
            }
        }
        
        public static string report_title_fuel_level_monitor {
            get {
                return ResourceManager.GetString("report_title_fuel_level_monitor", resourceCulture);
            }
        }
        
        public static string report_title_fuel_summary {
            get {
                return ResourceManager.GetString("report_title_fuel_summary", resourceCulture);
            }
        }
        
        public static string report_title_fuel_volume {
            get {
                return ResourceManager.GetString("report_title_fuel_volume", resourceCulture);
            }
        }
        
        public static string report_title_location_monitor {
            get {
                return ResourceManager.GetString("report_title_location_monitor", resourceCulture);
            }
        }
        
        public static string report_title_overtime_utilization {
            get {
                return ResourceManager.GetString("report_title_overtime_utilization", resourceCulture);
            }
        }
        
        public static string report_title_personal_logbook {
            get {
                return ResourceManager.GetString("report_title_personal_logbook", resourceCulture);
            }
        }
        
        public static string report_title_per_variable_display {
            get {
                return ResourceManager.GetString("report_title_per_variable_display", resourceCulture);
            }
        }
        
        public static string report_title_poi_activity {
            get {
                return ResourceManager.GetString("report_title_poi_activity", resourceCulture);
            }
        }
        
        public static string report_title_risk_management {
            get {
                return ResourceManager.GetString("report_title_risk_management", resourceCulture);
            }
        }
        
        public static string report_title_time_profile_utilization {
            get {
                return ResourceManager.GetString("report_title_time_profile_utilization", resourceCulture);
            }
        }
        
        public static string report_title_vehicle_score {
            get {
                return ResourceManager.GetString("report_title_vehicle_score", resourceCulture);
            }
        }
        
        public static string reset_dashboard_prompt {
            get {
                return ResourceManager.GetString("reset_dashboard_prompt", resourceCulture);
            }
        }
        
        public static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        public static string risk_management_description {
            get {
                return ResourceManager.GetString("risk_management_description", resourceCulture);
            }
        }
        
        public static string route_activity_description {
            get {
                return ResourceManager.GetString("route_activity_description", resourceCulture);
            }
        }
        
        public static string rpm_label {
            get {
                return ResourceManager.GetString("rpm_label", resourceCulture);
            }
        }
        
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        public static string select_y_axis {
            get {
                return ResourceManager.GetString("select_y_axis", resourceCulture);
            }
        }
        
        public static string server_connection_error {
            get {
                return ResourceManager.GetString("server_connection_error", resourceCulture);
            }
        }
        
        public static string snap_trip_to_road_label {
            get {
                return ResourceManager.GetString("snap_trip_to_road_label", resourceCulture);
            }
        }
        
        public static string speeding_label {
            get {
                return ResourceManager.GetString("speeding_label", resourceCulture);
            }
        }
        
        public static string speed_km_h_abbr {
            get {
                return ResourceManager.GetString("speed_km_h_abbr", resourceCulture);
            }
        }
        
        public static string speed_mph_abbr {
            get {
                return ResourceManager.GetString("speed_mph_abbr", resourceCulture);
            }
        }
        
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        public static string start_date {
            get {
                return ResourceManager.GetString("start_date", resourceCulture);
            }
        }
        
        public static string start_date_after_end_date_error {
            get {
                return ResourceManager.GetString("start_date_after_end_date_error", resourceCulture);
            }
        }
        
        public static string stopped_time_dashboard {
            get {
                return ResourceManager.GetString("stopped_time_dashboard", resourceCulture);
            }
        }
        
        public static string stopped_time_title {
            get {
                return ResourceManager.GetString("stopped_time_title", resourceCulture);
            }
        }
        
        public static string stop_duration {
            get {
                return ResourceManager.GetString("stop_duration", resourceCulture);
            }
        }
        
        public static string success_label {
            get {
                return ResourceManager.GetString("success_label", resourceCulture);
            }
        }
        
        public static string swerving_label {
            get {
                return ResourceManager.GetString("swerving_label", resourceCulture);
            }
        }
        
        public static string this_month {
            get {
                return ResourceManager.GetString("this_month", resourceCulture);
            }
        }
        
        public static string this_week {
            get {
                return ResourceManager.GetString("this_week", resourceCulture);
            }
        }
        
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        public static string time_h {
            get {
                return ResourceManager.GetString("time_h", resourceCulture);
            }
        }
        
        public static string time_min {
            get {
                return ResourceManager.GetString("time_min", resourceCulture);
            }
        }
        
        public static string title_activity_account_settings {
            get {
                return ResourceManager.GetString("title_activity_account_settings", resourceCulture);
            }
        }
        
        public static string title_application {
            get {
                return ResourceManager.GetString("title_application", resourceCulture);
            }
        }
        
        public static string title_b_licence_chart {
            get {
                return ResourceManager.GetString("title_b_licence_chart", resourceCulture);
            }
        }
        
        public static string title_custom_date_range {
            get {
                return ResourceManager.GetString("title_custom_date_range", resourceCulture);
            }
        }
        
        public static string title_exception_vs_distance_chart {
            get {
                return ResourceManager.GetString("title_exception_vs_distance_chart", resourceCulture);
            }
        }
        
        public static string title_favourite_reports {
            get {
                return ResourceManager.GetString("title_favourite_reports", resourceCulture);
            }
        }
        
        public static string title_fuel_consumption {
            get {
                return ResourceManager.GetString("title_fuel_consumption", resourceCulture);
            }
        }
        
        public static string title_fuel_consumption_graph {
            get {
                return ResourceManager.GetString("title_fuel_consumption_graph", resourceCulture);
            }
        }
        
        public static string title_fuel_efficiency_graph {
            get {
                return ResourceManager.GetString("title_fuel_efficiency_graph", resourceCulture);
            }
        }
        
        public static string title_least_utilised {
            get {
                return ResourceManager.GetString("title_least_utilised", resourceCulture);
            }
        }
        
        public static string title_map {
            get {
                return ResourceManager.GetString("title_map", resourceCulture);
            }
        }
        
        public static string title_most_utilised {
            get {
                return ResourceManager.GetString("title_most_utilised", resourceCulture);
            }
        }
        
        public static string title_personal_licence_chart {
            get {
                return ResourceManager.GetString("title_personal_licence_chart", resourceCulture);
            }
        }
        
        public static string title_share_report {
            get {
                return ResourceManager.GetString("title_share_report", resourceCulture);
            }
        }
        
        public static string title_total_exception_chart {
            get {
                return ResourceManager.GetString("title_total_exception_chart", resourceCulture);
            }
        }
        
        public static string title_trip_plotting {
            get {
                return ResourceManager.GetString("title_trip_plotting", resourceCulture);
            }
        }
        
        public static string title_t_licence_chart {
            get {
                return ResourceManager.GetString("title_t_licence_chart", resourceCulture);
            }
        }
        
        public static string title_units_of_measure {
            get {
                return ResourceManager.GetString("title_units_of_measure", resourceCulture);
            }
        }
        
        public static string title_vehicle_trip_activity_chart {
            get {
                return ResourceManager.GetString("title_vehicle_trip_activity_chart", resourceCulture);
            }
        }
        
        public static string title_vehicle_utilisation_distance_duration {
            get {
                return ResourceManager.GetString("title_vehicle_utilisation_distance_duration", resourceCulture);
            }
        }
        
        public static string title_vehicle_utilization {
            get {
                return ResourceManager.GetString("title_vehicle_utilization", resourceCulture);
            }
        }
        
        public static string toast_cache_cleared {
            get {
                return ResourceManager.GetString("toast_cache_cleared", resourceCulture);
            }
        }
        
        public static string toast_cannot_plot_trip_locations_missing {
            get {
                return ResourceManager.GetString("toast_cannot_plot_trip_locations_missing", resourceCulture);
            }
        }
        
        public static string toast_favourite_report_removed {
            get {
                return ResourceManager.GetString("toast_favourite_report_removed", resourceCulture);
            }
        }
        
        public static string toast_google_maps_not_available {
            get {
                return ResourceManager.GetString("toast_google_maps_not_available", resourceCulture);
            }
        }
        
        public static string toast_locating_vehicles {
            get {
                return ResourceManager.GetString("toast_locating_vehicles", resourceCulture);
            }
        }
        
        public static string toast_report_added_to_favourites {
            get {
                return ResourceManager.GetString("toast_report_added_to_favourites", resourceCulture);
            }
        }
        
        public static string toast_report_sharing_failed {
            get {
                return ResourceManager.GetString("toast_report_sharing_failed", resourceCulture);
            }
        }
        
        public static string toast_user_settings_updated {
            get {
                return ResourceManager.GetString("toast_user_settings_updated", resourceCulture);
            }
        }
        
        public static string toast_vehicle_X_location_unknown {
            get {
                return ResourceManager.GetString("toast_vehicle_X_location_unknown", resourceCulture);
            }
        }
        
        public static string toast_x_vehicles_located {
            get {
                return ResourceManager.GetString("toast_x_vehicles_located", resourceCulture);
            }
        }
        
        public static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        public static string top_5_best_utilized {
            get {
                return ResourceManager.GetString("top_5_best_utilized", resourceCulture);
            }
        }
        
        public static string top_5_best_utilized_subtitle {
            get {
                return ResourceManager.GetString("top_5_best_utilized_subtitle", resourceCulture);
            }
        }
        
        public static string top_5_current_fuel_level {
            get {
                return ResourceManager.GetString("top_5_current_fuel_level", resourceCulture);
            }
        }
        
        public static string top_5_current_fuel_level_subtitle {
            get {
                return ResourceManager.GetString("top_5_current_fuel_level_subtitle", resourceCulture);
            }
        }
        
        public static string top_5_drivers {
            get {
                return ResourceManager.GetString("top_5_drivers", resourceCulture);
            }
        }
        
        public static string top_5_driving_distance {
            get {
                return ResourceManager.GetString("top_5_driving_distance", resourceCulture);
            }
        }
        
        public static string top_5_driving_time {
            get {
                return ResourceManager.GetString("top_5_driving_time", resourceCulture);
            }
        }
        
        public static string top_5_fuel_consumption {
            get {
                return ResourceManager.GetString("top_5_fuel_consumption", resourceCulture);
            }
        }
        
        public static string top_5_fuel_volume {
            get {
                return ResourceManager.GetString("top_5_fuel_volume", resourceCulture);
            }
        }
        
        public static string top_5_least_utilized {
            get {
                return ResourceManager.GetString("top_5_least_utilized", resourceCulture);
            }
        }
        
        public static string top_5_most_utilized {
            get {
                return ResourceManager.GetString("top_5_most_utilized", resourceCulture);
            }
        }
        
        public static string top_5_worst_utilized {
            get {
                return ResourceManager.GetString("top_5_worst_utilized", resourceCulture);
            }
        }
        
        public static string top_5_worst_utilized_subtitle {
            get {
                return ResourceManager.GetString("top_5_worst_utilized_subtitle", resourceCulture);
            }
        }
        
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        public static string total_cost {
            get {
                return ResourceManager.GetString("total_cost", resourceCulture);
            }
        }
        
        public static string total_cost_of_ownership_description {
            get {
                return ResourceManager.GetString("total_cost_of_ownership_description", resourceCulture);
            }
        }
        
        public static string total_count {
            get {
                return ResourceManager.GetString("total_count", resourceCulture);
            }
        }
        
        public static string total_distance {
            get {
                return ResourceManager.GetString("total_distance", resourceCulture);
            }
        }
        
        public static string total_driving_time {
            get {
                return ResourceManager.GetString("total_driving_time", resourceCulture);
            }
        }
        
        public static string total_time {
            get {
                return ResourceManager.GetString("total_time", resourceCulture);
            }
        }
        
        public static string total_volume {
            get {
                return ResourceManager.GetString("total_volume", resourceCulture);
            }
        }
        
        public static string to_label {
            get {
                return ResourceManager.GetString("to_label", resourceCulture);
            }
        }
        
        public static string trip_end_label {
            get {
                return ResourceManager.GetString("trip_end_label", resourceCulture);
            }
        }
        
        public static string trip_logbook_title {
            get {
                return ResourceManager.GetString("trip_logbook_title", resourceCulture);
            }
        }
        
        public static string trip_recording {
            get {
                return ResourceManager.GetString("trip_recording", resourceCulture);
            }
        }
        
        public static string trip_start_label {
            get {
                return ResourceManager.GetString("trip_start_label", resourceCulture);
            }
        }
        
        public static string ubi_exceptions {
            get {
                return ResourceManager.GetString("ubi_exceptions", resourceCulture);
            }
        }
        
        public static string unknown_location {
            get {
                return ResourceManager.GetString("unknown_location", resourceCulture);
            }
        }
        
        public static string unknown_service_error {
            get {
                return ResourceManager.GetString("unknown_service_error", resourceCulture);
            }
        }
        
        public static string updating_report {
            get {
                return ResourceManager.GetString("updating_report", resourceCulture);
            }
        }
        
        public static string updating_reports {
            get {
                return ResourceManager.GetString("updating_reports", resourceCulture);
            }
        }
        
        public static string utilisation_period_percent {
            get {
                return ResourceManager.GetString("utilisation_period_percent", resourceCulture);
            }
        }
        
        public static string utilization {
            get {
                return ResourceManager.GetString("utilization", resourceCulture);
            }
        }
        
        public static string utilization_histogram {
            get {
                return ResourceManager.GetString("utilization_histogram", resourceCulture);
            }
        }
        
        public static string vehicle {
            get {
                return ResourceManager.GetString("vehicle", resourceCulture);
            }
        }
        
        public static string vehicle_description {
            get {
                return ResourceManager.GetString("vehicle_description", resourceCulture);
            }
        }
        
        public static string vehicle_dtc_dashboard {
            get {
                return ResourceManager.GetString("vehicle_dtc_dashboard", resourceCulture);
            }
        }
        
        public static string vehicle_group {
            get {
                return ResourceManager.GetString("vehicle_group", resourceCulture);
            }
        }
        
        public static string vehicle_group_average {
            get {
                return ResourceManager.GetString("vehicle_group_average", resourceCulture);
            }
        }
        
        public static string vehicle_score_description {
            get {
                return ResourceManager.GetString("vehicle_score_description", resourceCulture);
            }
        }
        
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        public static string vin_changed_dashboard {
            get {
                return ResourceManager.GetString("vin_changed_dashboard", resourceCulture);
            }
        }
        
        public static string violation_label {
            get {
                return ResourceManager.GetString("violation_label", resourceCulture);
            }
        }
        
        public static string volume {
            get {
                return ResourceManager.GetString("volume", resourceCulture);
            }
        }
        
        public static string volume_imperial_gallons {
            get {
                return ResourceManager.GetString("volume_imperial_gallons", resourceCulture);
            }
        }
        
        public static string volume_imperial_gallons_abbr {
            get {
                return ResourceManager.GetString("volume_imperial_gallons_abbr", resourceCulture);
            }
        }
        
        public static string volume_litres {
            get {
                return ResourceManager.GetString("volume_litres", resourceCulture);
            }
        }
        
        public static string volume_litres_abbr {
            get {
                return ResourceManager.GetString("volume_litres_abbr", resourceCulture);
            }
        }
        
        public static string volume_us_gallons {
            get {
                return ResourceManager.GetString("volume_us_gallons", resourceCulture);
            }
        }
        
        public static string volume_us_gallons_abbr {
            get {
                return ResourceManager.GetString("volume_us_gallons_abbr", resourceCulture);
            }
        }
        
        public static string welcome_label {
            get {
                return ResourceManager.GetString("welcome_label", resourceCulture);
            }
        }
        
        public static string work_hours {
            get {
                return ResourceManager.GetString("work_hours", resourceCulture);
            }
        }
        
        public static string work_time_driving {
            get {
                return ResourceManager.GetString("work_time_driving", resourceCulture);
            }
        }
        
        public static string x_vehicles {
            get {
                return ResourceManager.GetString("x_vehicles", resourceCulture);
            }
        }
        
        public static string yesterday {
            get {
                return ResourceManager.GetString("yesterday", resourceCulture);
            }
        }
    }
}
